### ISSUE TITLE
installed but can't see the back forwards button

### ISSUE THREAD

**Issue by oliverbevan** [grimmer0125/vscode-back-forward-button#1]
Sorry I'm a bit of a noob to vscode, can anyone help me out is there an extra step or something I'm missing?

Name: Back and Forward buttons
Id: grimmer.vscode-back-forward-button
Description: 
Version: 0.1.2
Publisher: grimmer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=grimmer.vscode-back-forward-button

**Comment by oliverbevan** [comment]
Ok i just found them in the bottem left corner of the screen, right after i opened this issue XD

**Comment by rijobro** [comment]
I just had to search for this issue to be able to find the buttons. Might be worth adding to `README.md` to make it obvious for future users.
