### ISSUE TITLE
won't install on mac/vscode

### ISSUE THREAD

**Issue by chovyprognos** [grimmer0125/vscode-back-forward-button#6]
It doesn't show up in extensions search and the "install" button on the vscode page doesn't do anything.

**Comment by grimmerk** [comment]
Could you supply more detail about your environment (e.g. Mac & VSCode version)? I use Mac and can not reproduce this issue.

Expect: 
After click install button,  the extension will be installed and later you can see the back-forward button on the states bar.

**Comment by grimmerk** [comment]
I'm closing it since no detail. Please reopen it if it happens in the recent version.
