### ISSUE TITLE
Arrows positioning

### ISSUE THREAD

**Issue by wachunei** [grimmer0125/vscode-back-forward-button#7]
First of all, thank you a lot for this extension!

I was wondering if it could be an option to place arrows on the top right of the tab bar:

![image](https://user-images.githubusercontent.com/1024246/113361575-b7fe4e80-9322-11eb-9567-84f5103c4b42.png)

Thanks again!

**Comment by grimmerk** [comment]
@wachunei 

Is this https://marketplace.visualstudio.com/items?itemName=nick-rudenko.back-n-forth what you want?

**Comment by wachunei** [comment]
Yes, Thank you!
